### ISSUE TITLE
Graphic bug on buttons on resize

### ISSUE THREAD

**Issue by igreen1** [andrewseamanco/sursum_website#1]
![image](https://user-images.githubusercontent.com/40191185/108573858-91340d80-72ca-11eb-8368-cae91bd4dd9c.png)

When at half size on my screen (1920x1080), this bug appears

**Comment by hallegv** [comment]
bug doesn't happen for me when viewport is 1920x1080 and at 50%. maybe it's a _you_ problem? check yourself. @igreen1
